namespace SignalR.Documentation.Models.View;

internal static class SocketDocsCss
{
    public const string Content = """
        :root{color-scheme:light;--ink:#182232;--muted:#667085;--line:#e4e7ec;--accent:#5650d6;--soft:#f6f7fb}
        *{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:28px}body{margin:0;color:var(--ink);background:#fff;font:14px/1.6 Inter,Segoe UI,Arial,sans-serif}
        [hidden]{display:none!important}a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}code{font:13px/1.6 Consolas,monospace;overflow-wrap:anywhere}
        aside{position:fixed;inset:0 auto 0 0;width:268px;background:#fafbfc;border-right:1px solid var(--line);padding:30px 22px;overflow:auto}
        .brand{display:flex;align-items:center;gap:6px;font-size:17px;font-weight:650;color:var(--ink);white-space:nowrap}.logo{display:inline-grid;place-items:center;width:29px;height:29px;margin-right:4px;border-radius:7px;background:var(--accent);color:white;font-size:22px}
        .search-label{display:block;font-size:12px;color:var(--muted);margin:32px 0 7px}input{width:100%;padding:10px 11px;border:1px solid #d0d5dd;border-radius:7px;background:white;color:var(--ink);font:inherit;font-size:12px}
        :focus-visible{outline:3px solid #aca7fa;outline-offset:3px}nav{margin-top:28px}nav a{display:flex;justify-content:space-between;color:#475467;padding:9px 10px;margin:4px -10px;border-radius:6px;overflow-wrap:anywhere}nav a:hover{background:#eeedf9;color:var(--accent);text-decoration:none}.eyebrow{font-size:11px;font-weight:700;letter-spacing:1.5px}.muted,.method-description{color:var(--muted)}.accent{color:var(--accent)}.aside-note{color:var(--muted);font-size:12px;margin-top:44px}
        main{margin-left:268px;max-width:1260px;padding:54px 60px 20px}header{padding-bottom:35px;border-bottom:1px solid var(--line);margin-bottom:36px}h1{font-size:38px;letter-spacing:-1.4px;line-height:1.2;margin:12px 0}h2{font-size:24px;letter-spacing:-.6px;margin:0}h3{font-size:13px;margin:23px 0 10px}.intro{font-size:16px;color:var(--muted)}.stats{display:flex;gap:13px;color:var(--muted);font-size:12px;margin-top:24px}.stats span{color:#b0b7c3}
        section{margin-bottom:40px;scroll-margin-top:24px}section>p{margin:6px 0 22px}.count{font-size:11px;font-weight:500;color:var(--muted);background:#eef0f4;border-radius:5px;padding:2px 7px}.section-heading{display:flex;align-items:center;gap:12px}
        .method,.model{border:1px solid var(--line);border-radius:8px;margin:10px 0;background:#fff;overflow:hidden}.method[open],.model[open]{border-color:#bcb8ee}summary{cursor:pointer}summary:hover{background:#fafaff}.method>summary,.model>summary{list-style:none;display:flex;align-items:center;gap:14px;padding:17px 20px}.method>summary::-webkit-details-marker,.model>summary::-webkit-details-marker{display:none}.method-description{margin-left:auto;font-size:12px;text-align:right}.chevron{color:var(--muted)}details[open]>summary>.chevron{transform:rotate(180deg)}.method-kind{background:#eeedfc;color:#5146bd;padding:3px 8px;border-radius:4px;font:700 10px/1.5 Consolas,monospace;letter-spacing:.7px}.method-body,.model-body{padding:0 24px 24px;border-top:1px solid var(--line)}.object-icon{font:700 14px Consolas,monospace;color:var(--accent)}
        .field{border-top:1px solid var(--line);padding:13px 0}.field-heading{display:flex;align-items:center;gap:12px;margin-bottom:4px}.field-heading>code{font-weight:700}.required{color:#aa3d49;font-size:11px}.field-heading>.muted{font-size:11px}.type-line{display:flex;align-items:center;flex-wrap:wrap;gap:10px}.type{color:var(--accent)}.nullable{background:#f0f2f5;color:#596579;border-radius:4px;padding:1px 5px;font-size:10px}.model-link{font-size:11px;margin-left:auto}.nested{margin:10px 0 0 5px;border-left:2px solid #e9e7f7;padding-left:15px}.nested>summary{color:#576276;font-size:12px;padding:3px 0}.nested>.type-line{margin-top:9px}.property-description,.enum-values,.recursive{font-size:12px;margin:6px 0 0}.qualified{font:11px Consolas,monospace;color:var(--muted);overflow-wrap:anywhere;margin-top:18px}.empty{padding:24px;background:var(--soft);border-radius:8px;color:var(--muted)}footer{border-top:1px solid var(--line);padding:24px 0;color:var(--muted);font-size:11px}
        @media(min-width:1450px){main{margin-left:calc(268px + (100vw - 1450px)/2)}}
        @media(max-width:850px){aside{position:relative;width:100%;padding:20px;border-right:0;border-bottom:1px solid var(--line)}.aside-note{display:none}nav{display:flex;gap:20px;align-items:center;margin-top:16px}nav a{gap:10px;margin:0}nav .eyebrow{display:none}.search-label{margin-top:18px}main{margin:0;padding:30px 20px}.method-description{display:none}h1{font-size:32px}.method>summary,.model>summary{padding:15px;gap:10px}.chevron{margin-left:auto}.method-body,.model-body{padding:0 15px 18px}}
        @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
        """;
}
